default_platform(:android)

platform :android do
  desc "Build & Upload Android Bundle (AAB) to Google Play Internal Track"
  lane :deploy_internal do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: 'internal',
      aab: '../app/build/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['GCP_PLAY_STORE_KEY']
    )
  end
end
